### ISSUE TITLE
No confirmation that data upload successfully

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#531]
Server: qa.pilrhealth.com
Page: /project/nusi_demo_2/participant/show/57153ab8e4b0080a4984fa33
User: ewohlers
Project: nusi_demo_2

I would like to come to the participant data view after data file is uploaded or have some confirmation that data was uploaded successfully.

**Comment by jmusacchio-gap** [comment]
Fixed it waiting for a deploy on QA

**Comment by plbrownupnorth** [comment]
Erica and PB tested this on May 19. Not fixed. Did change get pushed to qa?

**Comment by jmusacchio-gap** [comment]
It is not redirecting to participant data view?

**Comment by plbrownupnorth** [comment]
No. How do we check if it actually go pushed to qa?

**Comment by jmusacchio-gap** [comment]
Only by checking the deployed branch. It should be on QA, when working on new CalRQ feature I uploaded some files and got redirected to Search Data page.
