### ISSUE TITLE
Duplicate variable creation

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#645]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0804_2/project/components
User: eruud
Project: calorimetertest0804_2

Variables may be created with identical names since validation is done on code. We would like validation on code and names to prevent the creation of variables with identical names.

**Comment by jmusacchio-gap** [comment]
Refactored variable def creation and edition (frontend and backend). Added a new script to populate variable definition range cause on some cases was null/empty. Forced name to be unique as code.

**Comment by eruud** [comment]
Tested and it now rejects based on the name field as well.

If the name matches with case, there is a clear error that displays and it is rejected
If the name matches but has a different case, a less readable error is displayed (see below)
If it's an easy fix it would be nice if the simple error message was displayed in both cases.

![image](https://cloud.githubusercontent.com/assets/19293109/17863717/732a5b42-6860-11e6-84dc-3e8936361a78.png)
![image](https://cloud.githubusercontent.com/assets/19293109/17863724/7bd57cd6-6860-11e6-9b3e-b97288de5855.png)

**Comment by ijafir** [comment]
name validation now occurs. project calorimetertest0719-3 had template errors causing erratic behavior, those template errors were fixed and ready to be tested

**Comment by ewohlers1** [comment]
This still doesn't prevent duplicates with different letter case (Diet and diet or Sleep Threshold and sleep threshold). Can check on NuSI-0823 project.

**Comment by eruud** [comment]
Can we reject variables that are named the same but with different case? Currently you can name a variable the same as another with a different case and it will not be rejected. This also occurs with the code.
